version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/node:22.22
    environment:
      COREPACK_ENABLE_DOWNLOAD_PROMPT: "0"
    steps:
      - checkout
      - run: sudo corepack enable && pnpm --version
      - restore_cache:
          keys:
            - pnpm-deps-v1-{{ .Branch }}-{{ checksum "pnpm-lock.yaml" }}
            - pnpm-deps-v1-{{ .Branch }}-
            - pnpm-deps-v1-
      - run: pnpm config set store-dir ~/.pnpm-store && pnpm install --frozen-lockfile
      - save_cache:
          key: pnpm-deps-v1-{{ .Branch }}-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ~/.pnpm-store
      - run: pnpm run lint
  deploy:
    docker:
      - image: cimg/node:22.22
    steps:
      - checkout
      - run: curl $DEPLOY_ADDRESS

workflows:
  lint_and_test_maybe-deploy:
    jobs:
      - lint:
          filters:
            tags:
              only: /.*/
      - deploy:
          filters:
            tags:
              only: /^v\d+\.\d+.\d+-build\.\d+$/
            branches:
              ignore: /.*/
          requires:
            - lint
